-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.5.0.102
-- Module  Version: 5.7
--C:\lscc\diamond\3.5_x64\ispfpga\bin\nt64\scuba.exe -w -n pll0 -lang vhdl -synth synplify -arch ep5a00 -type pll -fin 8.192 -phase_cntl STATIC -fclkop 32.768 -fclkop_tol 0.0 -delay_cntl AUTO_NO_DELAY -fb_mode INTERNAL -extcap ENABLED -noclkos -noclkok -norst 

-- Tue Jun 21 12:27:48 2016

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library ecp2;
use ecp2.components.all;
-- synopsys translate_on

entity pll0 is
    port (
        CLK: in std_logic; 
        CLKOP: out std_logic; 
        LOCK: out std_logic);
end pll0;

architecture Structure of pll0 is

    -- internal signal declarations
    signal CLKOP_t: std_logic;
    signal CLKFB_t: std_logic;
    signal scuba_vlo: std_logic;
    signal CLK_t: std_logic;

    -- local component declarations
    component VLO
        port (Z: out std_logic);
    end component;
    component EPLLD
    -- synopsys translate_off
        generic (PLLCAP : in String; CLKOK_BYPASS : in String; 
                CLKOS_BYPASS : in String; CLKOP_BYPASS : in String; 
                DUTY : in Integer; PHASEADJ : in String; 
                PHASE_CNTL : in String; CLKOK_DIV : in Integer; 
                CLKFB_DIV : in Integer; CLKOP_DIV : in Integer; 
                CLKI_DIV : in Integer);
    -- synopsys translate_on
        port (CLKI: in std_logic; CLKFB: in std_logic; RST: in std_logic; 
            RSTK: in std_logic; DPAMODE: in std_logic; DRPAI3: in std_logic; 
            DRPAI2: in std_logic; DRPAI1: in std_logic; DRPAI0: in std_logic; 
            DFPAI3: in std_logic; DFPAI2: in std_logic; DFPAI1: in std_logic; 
            DFPAI0: in std_logic; CLKOP: out std_logic; CLKOS: out std_logic; 
            CLKOK: out std_logic; LOCK: out std_logic; CLKINTFB: out std_logic);
    end component;
    attribute PLLCAP : string; 
    attribute PLLTYPE : string; 
    attribute CLKOK_BYPASS : string; 
    attribute CLKOK_DIV : string; 
    attribute CLKOS_BYPASS : string; 
    attribute FREQUENCY_PIN_CLKOP : string; 
    attribute CLKOP_BYPASS : string; 
    attribute PHASE_CNTL : string; 
    attribute FDEL : string; 
    attribute DUTY : string; 
    attribute PHASEADJ : string; 
    attribute FREQUENCY_PIN_CLKI : string; 
    attribute CLKOP_DIV : string; 
    attribute CLKFB_DIV : string; 
    attribute CLKI_DIV : string; 
    attribute FIN : string; 
    attribute PLLCAP of PLLDInst_0 : label is "ENABLED";
    attribute PLLTYPE of PLLDInst_0 : label is "AUTO";
    attribute CLKOK_BYPASS of PLLDInst_0 : label is "DISABLED";
    attribute CLKOK_DIV of PLLDInst_0 : label is "2";
    attribute CLKOS_BYPASS of PLLDInst_0 : label is "DISABLED";
    attribute FREQUENCY_PIN_CLKOP of PLLDInst_0 : label is "32.768000";
    attribute CLKOP_BYPASS of PLLDInst_0 : label is "DISABLED";
    attribute PHASE_CNTL of PLLDInst_0 : label is "STATIC";
    attribute FDEL of PLLDInst_0 : label is "0";
    attribute DUTY of PLLDInst_0 : label is "8";
    attribute PHASEADJ of PLLDInst_0 : label is "0.0";
    attribute FREQUENCY_PIN_CLKI of PLLDInst_0 : label is "8.192000";
    attribute CLKOP_DIV of PLLDInst_0 : label is "32";
    attribute CLKFB_DIV of PLLDInst_0 : label is "4";
    attribute CLKI_DIV of PLLDInst_0 : label is "1";
    attribute FIN of PLLDInst_0 : label is "8.192000";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    scuba_vlo_inst: VLO
        port map (Z=>scuba_vlo);

    PLLDInst_0: EPLLD
        -- synopsys translate_off
        generic map (PLLCAP=> "ENABLED", CLKOK_BYPASS=> "DISABLED", 
        CLKOK_DIV=>  2, CLKOS_BYPASS=> "DISABLED", CLKOP_BYPASS=> "DISABLED", 
        PHASE_CNTL=> "STATIC", DUTY=>  8, PHASEADJ=> "0.0", CLKOP_DIV=>  32, 
        CLKFB_DIV=>  4, CLKI_DIV=>  1)
        -- synopsys translate_on
        port map (CLKI=>CLK_t, CLKFB=>CLKFB_t, RST=>scuba_vlo, 
            RSTK=>scuba_vlo, DPAMODE=>scuba_vlo, DRPAI3=>scuba_vlo, 
            DRPAI2=>scuba_vlo, DRPAI1=>scuba_vlo, DRPAI0=>scuba_vlo, 
            DFPAI3=>scuba_vlo, DFPAI2=>scuba_vlo, DFPAI1=>scuba_vlo, 
            DFPAI0=>scuba_vlo, CLKOP=>CLKOP_t, CLKOS=>open, CLKOK=>open, 
            LOCK=>LOCK, CLKINTFB=>CLKFB_t);

    CLKOP <= CLKOP_t;
    CLK_t <= CLK;
end Structure;

-- synopsys translate_off
library ecp2;
configuration Structure_CON of pll0 is
    for Structure
        for all:VLO use entity ecp2.VLO(V); end for;
        for all:EPLLD use entity ecp2.EPLLD(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
